dist: trusty

jobs:
  include:
    - stage: build & push docker image
      script:
      - docker build -t python-app .
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - docker tag $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com:latest
      - docker push $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com:latest
